import {
  Heart,
  Star,
  Sparkles,
  Zap,
  Moon,
  Sun,
  Cloud,
  Flower2,
  Leaf,
  Coffee,
  Quote,
  Smile,
  Music,
  Camera,
  HeartHandshake,
  Wand2,
  Rocket,
  Crown,
  Flame,
  Droplets
} from "lucide-react";

export const AESTHETIC_ICONS = [
  { name: "Heart", icon: Heart },
  { name: "Star", icon: Star },
  { name: "Sparkles", icon: Sparkles },
  { name: "Zap", icon: Zap },
  { name: "Moon", icon: Moon },
  { name: "Sun", icon: Sun },
  { name: "Cloud", icon: Cloud },
  { name: "Flower", icon: Flower2 },
  { name: "Leaf", icon: Leaf },
  { name: "Coffee", icon: Coffee },
  { name: "Quote", icon: Quote },
  { name: "Smile", icon: Smile },
  { name: "Music", icon: Music },
  { name: "Camera", icon: Camera },
  { name: "HeartHandshake", icon: HeartHandshake },
  { name: "Wand", icon: Wand2 },
  { name: "Rocket", icon: Rocket },
  { name: "Crown", icon: Crown },
  { name: "Flame", icon: Flame },
  { name: "Water", icon: Droplets }
];
